# Generated by Django 5.2.17 on 2026-09-16 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(max_length=100, unique=True)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('product_category', models.CharField(blank=True, max_length=200)),
                ('product_sub_category', models.CharField(blank=True, max_length=200)),
                ('collection_name', models.CharField(blank=True, max_length=200)),
                ('color_collection', models.CharField(blank=True, max_length=200)),
                ('product_color', models.CharField(blank=True, max_length=200)),
                ('product_name', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('bullets', models.TextField(blank=True)),
                ('set_includes', models.TextField(blank=True)),
                ('product_weight', models.CharField(blank=True, max_length=100)),
                ('materials', models.CharField(blank=True, max_length=300)),
                ('product_dimensions', models.TextField(blank=True)),
                ('assembly_required', models.CharField(blank=True, max_length=10)),
                ('is_a_set', models.CharField(blank=True, max_length=10)),
                ('stackable', models.CharField(blank=True, max_length=10)),
                ('country_of_origin', models.CharField(blank=True, max_length=100)),
                ('item_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('map_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('msrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipping_method', models.CharField(blank=True, max_length=100)),
                ('total_box_count', models.IntegerField(blank=True, null=True)),
                ('pallet_count', models.IntegerField(blank=True, null=True)),
                ('shipping_weight', models.CharField(blank=True, max_length=100)),
                ('total_cbm', models.CharField(blank=True, max_length=100)),
                ('package_dimensions', models.TextField(blank=True)),
                ('product_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('is_valid', models.BooleanField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop_app.product')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviewers/')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
