# Generated by Django 5.2.17 on 2026-09-16 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(default=0.0)),
                ('alternatives_json', models.TextField(blank=True)),
                ('is_low_confidence', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('needs_review', 'Needs Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='needs_review', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('predicted_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shop_app.category')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='shop_app.product')),
            ],
        ),
    ]
